---
# ansible-lint configuration

profile: production

skip_list:
  - key-order
  - var-naming[non-string]

exclude_paths:
  - mkdocs.yml
  - panos_policy_automation/mkdocs.yml
  - .github
  - panos_policy_automation/.github
