from json import JSONDecodeError

DOCUMENTATION = '''
name: panos_op_stdout_to_dict
short_description: Convert panos_op stdout to dictionary
description:
  - Takes the result dictionary generated by the panos_op command and converts stdout to a dictionary.
  - Makes it easier to manipulate the JSON output from PAN-OS operational commands.
version_added: "1.0.0"
author:
  - PaloAlto Networks (@PaloAltoNetworks)
options:
  _input:
    description:
      - The result dictionary from panos_op command containing stdout field
    type: dict
    required: true
'''

EXAMPLES = '''
# Convert panos_op stdout to dictionary
- name: Get all connected devices
  paloaltonetworks.panos.panos_op:
    provider: "{{ provider }}"
    cmd: "show devices connected"
  register: policy_creation__show_devices_output

- name: Set JSON Object for stdout
  ansible.builtin.set_fact:
    policy_creation__show_devices_output_dict: >
      {{ policy_creation__show_devices_output | paloaltonetworks.panos_policy_automation.panos_op_stdout_to_dict }}
'''

RETURN = '''
_value:
  description: Parsed dictionary from stdout JSON
  type: dict
  returned: always
'''

import json


class PanosStdoutParseError(Exception):
    """Raises when the device returns invalid JSON"""
    pass


def panos_op_stdout_to_dict(result):
    """Takes the result dictionary generated by the panos_op command and converts stdout to a dictionary,
    making it easier to manipulate."""
    try:
        return json.loads(result.get("stdout"))
    except JSONDecodeError as e:
        raise PanosStdoutParseError("Failed to parse result as json: " + result.get("stdout")) from e


class FilterModule(object):
    def filters(self):
        return {
            'panos_op_stdout_to_dict': panos_op_stdout_to_dict
        }
